### ISSUE TITLE
bump version to v0.2.0?

### ISSUE THREAD

**Issue by axiangcoding** [axiangcoding/wt-profile-tool#12]
@RaidFourms Should we bump the version to v0.2.0, considering that the API has been modified?

**Comment by RaidFourms** [comment]
> @RaidFourms Should we bump the version to v0.2.0, considering that the API has been modified?

Your repo, your version 

But yes, I'd say so, even if it's pretty minor 

Also, are you OK with me adding a pr for a new class?

**Comment by axiangcoding** [comment]
@RaidFourms Okay, I'll handle the publishing. I think I can wait until your PR is over. As for the PR, just make sure that ci passes. 👍
