### ISSUE TITLE
Add param `count` to search_userid_by_prefix_nick

### ISSUE THREAD

**Issue by axiangcoding** [axiangcoding/wt-profile-tool#20]
Add param `count` to search_userid_by_prefix_nick, allow to customie return user count.

**Comment by RaidFourms** [comment]
I've noticed that the amount returned with that is very inconsistent - 1 returns 3, 2 returns 5, 3 returns 9 and so on, so maybe we can implement a client size limiter

**Comment by axiangcoding** [comment]
> I've noticed that the amount returned with that is very inconsistent - 1 returns 3, 2 returns 5, 3 returns 9 and so on, so maybe we can implement a client size limiter

I will look into it. If our limit is different from the `count` passed to params, maybe we will change the naming

**Comment by axiangcoding** [comment]
> I've noticed that the amount returned with that is very inconsistent - 1 returns 3, 2 returns 5, 3 returns 9 and so on, so maybe we can implement a client size limiter

It seems that this `count` is not the number returned as we understand it, but has other meanings. Maybe adding this `count` will confuse the real meaning of it. I think this issue can be closed
