### ISSUE TITLE
Better way to discern between battle types 

### ISSUE THREAD

**Issue by RaidFourms** [axiangcoding/wt-profile-tool#23]
Right now, the only way to see different stats for each game mode is 0/Null for arcade and 1 for realistic under battle_type. Don't know what 2 is, either sim or realistic

**Comment by RaidFourms** [comment]
> Unfortunately, I currently have no idea what 2 represents. 
> 
> https://github.com/axiangcoding/wt-profile-tool/blob/a4fedfb60f9b79c8aec596be54cfd44aab07d9e5/wt_profile_tool/schema/profile.py#L61
> 
> Later I will refer to the display in the game client to explain the meaning of these fields.

Isn't hardcore just the internal name for sim? I was thinking it before, but a lot of vehicles showed up under it that I don't remember playing in it. In the morning I'll check

**Comment by axiangcoding** [comment]
> Isn't hardcore just the internal name for sim? I was thinking it before, but a lot of vehicles showed up under it that I don't remember playing in it. In the morning I'll check
i have no idea about it. just get those define from that .java file. Anyway, if i found something related, i will add it to README.md

**Comment by axiangcoding** [comment]
Just comfirm, HARDCORE = 2 Simulator battle
