### ISSUE TITLE
Publish on PyPi?

### ISSUE THREAD

**Issue by RaidFourms** [axiangcoding/wt-profile-tool#3]

**Comment by axiangcoding** [comment]
Sure. I want to make it as a tool for usage. Any doubt?

**Comment by RaidFourms** [comment]
> Sure. I want to make it as a tool for usage. Any doubt?

Nope :D

I just wanted to publish it soon as possible as submodules keep bugging out for me and it's much easier to use pip.

As for keeping it public, I think you definitely should, unless Gaijin specifically tries to patch it, as they've been known to try and prevent scraping

**Comment by axiangcoding** [comment]
> > Sure. I want to make it as a tool for usage. Any doubt?
> 
> Nope :D
> 
> I just wanted to publish it soon as possible as submodules keep bugging out for me and it's much easier to use pip.
> 
> As for keeping it public, I think you definitely should, unless Gaijin specifically tries to patch it, as they've been known to try and prevent scraping

I also think it's worth publishing it on PyPI. I will finish preparing this package for release in the evening (few hours later, i'm working now :( ).
After completing the release, I think we can develop this project properly.

**Comment by RaidFourms** [comment]
> > > Sure. I want to make it as a tool for usage. Any doubt?
> > 
> > 
> > Nope :D
> > I just wanted to publish it soon as possible as submodules keep bugging out for me and it's much easier to use pip.
> > As for keeping it public, I think you definitely should, unless Gaijin specifically tries to patch it, as they've been known to try and prevent scraping
> 
> I also think it's worth publishing it on PyPI. I will finish preparing this package for release in the evening (few hours later, i'm working now :( ). After completing the release, I think we can develop this project properly.

sounds good mate o7

**Comment by axiangcoding** [comment]
@RaidFourms hi, this project is pushed to PyPI and TestPyPI. Now we can develop normally.
